site_name: MkDocs песочница
site_description: Этот сайт используется для изучения веб-разработки на Python с использованием MkDocs.
site_author: Салимов Сергей
copyright: '2024'

repo_url: https://github.com/mrskycriper/mkdocs-site-python

theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true
  custom_dir: 'custom_theme/'

nav:
  - Главная: index.md
  - Резюме: cv.md
  - Отчёты:
    - Практика 1: reports/lab-1.md
    - Практика 2: reports/lab-2.md