site_name: MkDocs песочница
site_description: Этот сайт используется для изучения веб-разработки на Python с использованием MkDocs.
site_author: Салимов Сергей
# Custom
site_date: 2024

repo_url: https://github.com/mrskycriper/mkdocs-site-python

theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true
